name: API Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: newman run postman/collection.json