name: CI Pipeline

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  api-tests:
    name: API Tests
    runs-on: ubuntu-latest    
    steps:
      - name: run newman
      - uses: actions/checkout@v3
      - run: npx newman run collection.json